name: resumemaker
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  path_provider: ^2.0.11
  random_avatar: ^0.0.7
  dropdown_button2: ^1.8.8
#  file_picker: ^5.2.2
  syncfusion_flutter_datepicker: ^20.3.50
  intl: ^0.17.0 #dateformate
  dots_indicator: ^2.1.0
  font_awesome_flutter: ^10.2.1
  bubble_bottom_bar: ^2.0.0
  pdf: ^3.8.4
  open_file: ^3.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  animated_native_splash: ^1.3.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

animated_native_splash:
  # color is the only required parameter.  It sets the background color of your splash screen.
  jsonFile: assets/splash.json