// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmUEWfivjdju5puc-zzePJWQaMTroxqfE',
    appId: '1:530673871314:web:161e4c9ccb53787755400b',
    messagingSenderId: '530673871314',
    projectId: 'card-resume-builder',
    authDomain: 'card-resume-builder.firebaseapp.com',
    storageBucket: 'card-resume-builder.appspot.com',
    measurementId: 'G-9PD70QF6NY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjaMe7B1v96tUbT29ZskbLVvsPhK71lnk',
    appId: '1:530673871314:android:92d4f9524569954f55400b',
    messagingSenderId: '530673871314',
    projectId: 'card-resume-builder',
    storageBucket: 'card-resume-builder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNZaKeFqPnHURO6dH2JMFGOMuTxOQskB8',
    appId: '1:530673871314:ios:80f649a2e677fa1455400b',
    messagingSenderId: '530673871314',
    projectId: 'card-resume-builder',
    storageBucket: 'card-resume-builder.appspot.com',
    iosClientId: '530673871314-0bcd019kp87t7u2cbrsieojp9m7b9te8.apps.googleusercontent.com',
    iosBundleId: 'com.example.resumemaker',
  );
}
